icons_format = "{icon}"

[theme]
theme = "modern"

[icons]
icons = "awesome5"

[[block]]
block = "cpu"
format = " $icon $utilization "
format_alt = " $icon $frequency{ $boost|} "
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

# [[block]]
# block = "disk_space"
# path = "/"
# info_type = "available"
# alert_unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0
# format = "$icon $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
warning_mem = 80
critical_mem = 90

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%r') "

[[block]]
block = "custom"
command = "sed 's/  //' <(curl 'https://wttr.in/?format=1' -s)"
interval = 600

[[block]]
block = "custom"
command = "echo \uf030" # assumes fontawesome icons
interval = "once"
[[block.click]]
button = "left"
cmd = "sh ~/.config/i3status-rust/scripts/screenshot.sh"


[[block]]
block = "menu"
text = " \uf011 "
[[block.items]]
display = " -&gt;   Sleep   &lt;-"
cmd = "systemctl suspend"
[[block.items]]
display = " -&gt; Power Off &lt;-"
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = " -&gt;  Reboot   &lt;-"
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"
